@url_dev = http://localhost:3070/v1/api

### signup

POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "tuanh",
    "email": "anhtudo96@gmail.com",
    "password": "123tuanh"
}