@url_dev = http://localhost:3070/v1/api

### signup

POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 20dcb72b692079ccb068f9caeb64f798bb10026bf5781a7238f44d07dd1b34f3d4b12ac100c81b155ced3c38a8b9c2bd639d7525fc7062df774a5c7e331e65aa

{
    "name": "tuanh",
    "email": "anhtudo93@gmail.com",
    "password": "123tuanh"
}

### signin

POST {{url_dev}}/shop/signin
Content-Type: application/json
x-api-key: 20dcb72b692079ccb068f9caeb64f798bb10026bf5781a7238f44d07dd1b34f3d4b12ac100c81b155ced3c38a8b9c2bd639d7525fc7062df774a5c7e331e65aa

{
    "email": "anhtudo93@gmail.com",
    "password": "123tuanh"
}

### logout

POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: 20dcb72b692079ccb068f9caeb64f798bb10026bf5781a7238f44d07dd1b34f3d4b12ac100c81b155ced3c38a8b9c2bd639d7525fc7062df774a5c7e331e65aa
x-client-id: 6546a3257fe40565da5822f8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTNhY2E0MmM5NGMwNmY5NWIzNWZlOTEiLCJlbWFpbCI6ImFuaHR1ZG85M0BnbWFpbC5jb20iLCJpYXQiOjE2OTgzNTMxODksImV4cCI6MTY5ODUyNTk4OX0.AFAD0S3-RXpfV6-hB3LXtARONHYodiNfn7azFySa3vE


### handle refresh token

POST {{url_dev}}/shop/handleRefreshToken
Content-Type: application/json
x-api-key: 20dcb72b692079ccb068f9caeb64f798bb10026bf5781a7238f44d07dd1b34f3d4b12ac100c81b155ced3c38a8b9c2bd639d7525fc7062df774a5c7e331e65aa
x-client-id: 6546a3257fe40565da5822f8
x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTQ2YTMyNTdmZTQwNTY1ZGE1ODIyZjgiLCJlbWFpbCI6ImFuaHR1ZG85M0BnbWFpbC5jb20iLCJpYXQiOjE3MDAwNzUyNzUsImV4cCI6MTcwMDY4MDA3NX0.tqpEE6hjZ4XUcif7isOdxV9IeI_EPXAO52NSWBkU4xM


### create product

POST {{url_dev}}/product
Content-Type: application/json
x-api-key: 20dcb72b692079ccb068f9caeb64f798bb10026bf5781a7238f44d07dd1b34f3d4b12ac100c81b155ced3c38a8b9c2bd639d7525fc7062df774a5c7e331e65aa
x-client-id: 6546a3257fe40565da5822f8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTQ2YTMyNTdmZTQwNTY1ZGE1ODIyZjgiLCJlbWFpbCI6ImFuaHR1ZG85M0BnbWFpbC5jb20iLCJpYXQiOjE3MDE3OTIyODYsImV4cCI6MTcwMTk2NTA4Nn0.7Fvq0QbK-1ZO1bOaAJXOdISxboOfM0mZGFU2PyKniNg

{
    "product_name": "IPhone 12 Pro max",
    "product_description": "Máy tính bảng 22222",
    "product_price": 1000000,
    "product_type": "Electronics",
    "product_thumb": "product_thumb",
    "product_quantity": 5,
    "product_attributes": {
        "manufacturer": "Apple123",
        "model": "iPhone 12",
        "color": "Red"
    }
}

### Create a product furniture

POST {{url_dev}}/product
Content-Type: application/json
x-api-key: 20dcb72b692079ccb068f9caeb64f798bb10026bf5781a7238f44d07dd1b34f3d4b12ac100c81b155ced3c38a8b9c2bd639d7525fc7062df774a5c7e331e65aa
x-client-id: 6546a3257fe40565da5822f8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTQ2YTMyNTdmZTQwNTY1ZGE1ODIyZjgiLCJlbWFpbCI6ImFuaHR1ZG85M0BnbWFpbC5jb20iLCJpYXQiOjE3MDIyMzY3NjcsImV4cCI6MTcwMjQwOTU2N30.A5rM5XaMXskbZUhrCLEPAQRSphIuxpd46RtaMX_Qows

{
    "product_name": "Clothing max",
    "product_description": "Máy tính bảng",
    "product_price": 1000000,
    "product_type": "Clothing",
    "product_thumb": "product_thumb",
    "product_quantity": 5,
    "product_attributes": {
        "brand": "Clothing1",
        "size": "11",
        "material": "CarbonFiber"
    }
}

### Update product by Shop

PATCH {{url_dev}}/product/6576180fc43c4436813c93c2
Content-Type: application/json
x-api-key: 20dcb72b692079ccb068f9caeb64f798bb10026bf5781a7238f44d07dd1b34f3d4b12ac100c81b155ced3c38a8b9c2bd639d7525fc7062df774a5c7e331e65aa
x-client-id: 6546a3257fe40565da5822f8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTQ2YTMyNTdmZTQwNTY1ZGE1ODIyZjgiLCJlbWFpbCI6ImFuaHR1ZG85M0BnbWFpbC5jb20iLCJpYXQiOjE3MDIzMjEyNzYsImV4cCI6MTcwMjQ5NDA3Nn0.mEhVpimPYL4alhD9G4d3PSexfWnbOs76kxP7Yw5EldI

{
    "product_attributes": {
        "size": "33",
        "material": "CarbonFiber33"
    },
    "product_type": "Clothing"
}

### Get all draft for shop

GET {{url_dev}}/product/drafts/all
Content-Type: application/json
x-api-key: 20dcb72b692079ccb068f9caeb64f798bb10026bf5781a7238f44d07dd1b34f3d4b12ac100c81b155ced3c38a8b9c2bd639d7525fc7062df774a5c7e331e65aa
x-client-id: 6546a3257fe40565da5822f8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTQ2YTMyNTdmZTQwNTY1ZGE1ODIyZjgiLCJlbWFpbCI6ImFuaHR1ZG85M0BnbWFpbC5jb20iLCJpYXQiOjE3MDU1OTU2MDgsImV4cCI6MTcwNTc2ODQwOH0.liURw3q7vyfCSofqWJIN7u3hSLw6mkiGDzY2Y5dcSgA


### Get all published for shop

GET {{url_dev}}/product/published/all
Content-Type: application/json
x-api-key: 20dcb72b692079ccb068f9caeb64f798bb10026bf5781a7238f44d07dd1b34f3d4b12ac100c81b155ced3c38a8b9c2bd639d7525fc7062df774a5c7e331e65aa
x-client-id: 6546a3257fe40565da5822f8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTQ2YTMyNTdmZTQwNTY1ZGE1ODIyZjgiLCJlbWFpbCI6ImFuaHR1ZG85M0BnbWFpbC5jb20iLCJpYXQiOjE3MDIzMjEyNzYsImV4cCI6MTcwMjQ5NDA3Nn0.mEhVpimPYL4alhD9G4d3PSexfWnbOs76kxP7Yw5EldI


### Publish product by Shop

POST {{url_dev}}/product/publish/6576180fc43c4436813c93c2
Content-Type: application/json
x-api-key: 20dcb72b692079ccb068f9caeb64f798bb10026bf5781a7238f44d07dd1b34f3d4b12ac100c81b155ced3c38a8b9c2bd639d7525fc7062df774a5c7e331e65aa
x-client-id: 6546a3257fe40565da5822f8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTQ2YTMyNTdmZTQwNTY1ZGE1ODIyZjgiLCJlbWFpbCI6ImFuaHR1ZG85M0BnbWFpbC5jb20iLCJpYXQiOjE3MDIyMzg1MDYsImV4cCI6MTcwMjQxMTMwNn0.v0A-A59_kneti6TLnUGTnNn8vilf28oA81BLDLNNznY


### Search product by key

GET {{url_dev}}/product/search/Clothing 
Content-Type: application/json
x-api-key: 20dcb72b692079ccb068f9caeb64f798bb10026bf5781a7238f44d07dd1b34f3d4b12ac100c81b155ced3c38a8b9c2bd639d7525fc7062df774a5c7e331e65aa

### Find all products

GET {{url_dev}}/product
Content-Type: application/json
x-api-key: 20dcb72b692079ccb068f9caeb64f798bb10026bf5781a7238f44d07dd1b34f3d4b12ac100c81b155ced3c38a8b9c2bd639d7525fc7062df774a5c7e331e65aa

### Find product

GET {{url_dev}}/product/6564e5fd1fec969847285e28
Content-Type: application/json
x-api-key: 20dcb72b692079ccb068f9caeb64f798bb10026bf5781a7238f44d07dd1b34f3d4b12ac100c81b155ced3c38a8b9c2bd639d7525fc7062df774a5c7e331e65aa